steps:
  # Paso 1: Construir la imagen Docker desde la carpeta Backend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/rivera-test:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/rivera-test:latest'
      - './Backend'
    
  # Paso 2: Subir la imagen a Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/rivera-test:$COMMIT_SHA'
    
  # Paso 3: Desplegar en Cloud Run con variables de entorno
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'rivera-test'
      - '--image'
      - 'gcr.io/$PROJECT_ID/rivera-test:$COMMIT_SHA'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--max-instances'
      - '2'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=4000,JWT_SECRET=$$JWT_SECRET,JWT_EXPIRES=$$JWT_EXPIRES,DB_URI=$$DB_URI,CLOUDINARY_NAME=$$CLOUDINARY_NAME,CLOUDINARY_API_KEY=$$CLOUDINARY_API_KEY,CLOUDINARY_API_SECRET=$$CLOUDINARY_API_SECRET,USER_EMAIL=$$USER_EMAIL,USER_PASS=$$USER_PASS,ADMIN_EMAIL=$$ADMIN_EMAIL,ADMIN_PASSWORD=$$ADMIN_PASSWORD,TWILIO_ACCOUNT_SID=$$TWILIO_ACCOUNT_SID,TWILIO_AUTH_TOKEN=$$TWILIO_AUTH_TOKEN,TWILIO_PHONE_NUMBER=$$TWILIO_PHONE_NUMBER,GOOGLE_CLIENT_ID=$$GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET=$$GOOGLE_CLIENT_SECRET,CAJA_CHICA_PASSWORD_REINTEGRO=$$CAJA_CHICA_PASSWORD_REINTEGRO'

images:
  - 'gcr.io/$PROJECT_ID/rivera-test:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/rivera-test:latest'

options:
  logging: CLOUD_LOGGING_ONLY